### ISSUE TITLE
Swift 5.2 import issue

### ISSUE THREAD

**Issue by tcamin** [mxcl/swift-sh#107]
There seems to be an issue with import of modules that have a repo name that doesn't match module name.

This import is working with Swift 5.1
`import SourceKittenFramework  // jpsim/SourceKitten`

but fails when using Swift 5.2 (Xcode 11.4 beta) with the following error:

```/Users/me/Library/Developer/swift-sh.cache/report: error: manifest parse error: target 'report' depends on an unknown package 'SourceKittenFramework'```

**Comment by mxcl** [comment]
Can you include the generated `Package.swift` and `deps.json`?

    /Users/me/Library/Developer/swift-sh.cache

**Comment by tcamin** [comment]
```
❯ cat Package.swift
// swift-tools-version:5.2
import PackageDescription

let pkg = Package(name: "report")

pkg.products = [
    .executable(name: "report", targets: ["report"])
]
pkg.dependencies = [
    .package(url: "https://github.com/jpsim/SourceKitten.git", Version(0,0,0)...Version(1_000_000,0,0))
]
pkg.targets = [
    .target(name: "report", dependencies: ["SourceKittenFramework"], path: ".", sources: ["main.swift"])
]

#if swift(>=5) && os(macOS)
pkg.platforms = [
   .macOS(.v10_15)
]
#endif
```

```
❯ cat deps.json
[{"dependencyName":"https:\/\/github.com\/jpsim\/SourceKitten.git","constraint":"latest","importName":"SourceKittenFramework"}]%
```

**Comment by mxcl** [comment]
SwiftKittenFramework is the correct module name. So this is unexpected.

**Comment by tcamin** [comment]
Good news, I tried with Xcode 11.4 beta 2 and the issue seems to be fixed!
