### ISSUE TITLE
stdin is read and evaluated from script if stdin isn’t TTY even when invoking swift-sh -h

### ISSUE THREAD

**Issue by pcr910303** [mxcl/swift-sh#108]
I’m not sure if this is intended or not, but `swift-sh` tries to [read stdin even with the flags `-h` when stdin isn’t a TTY](https://github.com/mxcl/swift-sh/blob/master/Sources/Command/CommandLine.usage.swift#L146). I’m not sure if this is intended, but AFAIU `-- -h` does the same thing, right? I believe that just printing the help message would be more consistent and less surprising.

For context, I’m trying to [add `swift-sh` on the Homebrew core tap](https://github.com/Homebrew/homebrew-core/pull/49956), and it looks like [the test (which is just checking the help message) is failing](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/57372/) because the stdin isn’t a TTY in the testing environment so it tries to read from it, and (due to reasons I don’t know) [errors due to the sandbox](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/57372/version=catalina/testReport/junit/brew-test-bot/catalina/test_swift_sh/) and [returns 2](https://github.com/mxcl/swift-sh/blob/master/Sources/main.swift#L33).

I would like the formula included in the main tap, so I would like if you can consider to remove the conditional behavior. I also can open a (trivial) PR removing the conditional if it’s preferable. 

Thanks.

**Comment by mxcl** [comment]
Yeah this probably incorrect behavior, will merge.
