### ISSUE TITLE
local repo dep. not found in 1.17.0 ; it worked fine in 1.16.1

### ISSUE THREAD

**Issue by ivrusuboca** [mxcl/swift-sh#112]
Hi Max - firstly - thank you very much, indeed, for writing swift-sh ; it suits my needs perfectly !

Unfortunately I upgraded to 1.17.0 only few days ago and I noticed my scripts do not work anymore . 

The layout I am using them is simple : my scripts reside inside a folder called Scripts/ which in turn resides inside my Swift library ; please visit this repository I created and which shows the break : https://github.com/ivrusuboca/mylib 

The README describes how it works in 1.16.1 and what errors I am getting when running under 1.17.0 .

May I kindly advise about this break ? 

Thank you. Ionut.

**Comment by mxcl** [comment]
Try 2.0.0.

FYI this bug report didn’t provide enough information that I can be sure I fixed your issue.

**Comment by ivrusuboca** [comment]
> Try 2.0.0.
> 
> 
> 
> FYI this bug report didn’t provide enough information that I can be sure I fixed your issue.

Hi Max - thank you for the reply . All's good now - 1.18.0 seems working Ok already ; will upgrade to 2.0.0 shortly. 

I've just closed the ticket . 

Regards. Ionut.
