### ISSUE TITLE
brew v1.18.0 doesn't seem to have code from github v1.18.0

### ISSUE THREAD

**Issue by adam-fowler** [mxcl/swift-sh#118]
I updated swift-sh to latest using your tap `brew install mxcl/made/swift-sh` but this doesn't seem to have the code that is associated with v1.18.0 in github. ie the swift 5.2 dependencies fixes.

If I build the project locally everything is fine. It I use the brew install it runs an older version of the code. You can verify this with the following swift script
```
#!/usr/bin/swift sh
import ArgumentParser   // apple/swift-argument-parser ~> 0.0.1
```

**Comment by Frizlab** [comment]
Probably related: https://github.com/mxcl/homebrew-made/issues/9

**Comment by mxcl** [comment]
Should be fixed, bottle published to my tap.
