### ISSUE TITLE
Using ArgumentParser with Swift 5.2

### ISSUE THREAD

**Issue by cwoloszynski77** [mxcl/swift-sh#120]
When trying to use the new 'ArgumentParser' in a project with Swift5.2 on my machine (MacOSX Catalina, 10.15.5), I get an error when trying to run the following directly, but when I do a 'swift sh eject' and then build, it works.

#!/usr/bin/swift sh

import ArgumentParser // apple/swift-argument-parser

struct PostData: ParsableCommand {
    @Argument() var hostname: String

    static func run() {
        print("running")
    }
}

PostData.run()

The error I get is:

'postData' /Users/charlie/Library/Developer/swift-sh.cache/cbf17a619a0a1e175271a55751e0aeb3: error: dependency 'ArgumentParser' in target 'postData' requires explicit declaration; reference the package in the target dependency with '.product(name: "ArgumentParser", package: "swift-argument-parser")'

Am I doing something wrong or is this an issue with Swift 5.2 or a change in SPM?

**Comment by cwoloszynski77** [comment]
Looking at #115, it looks like this is the problem where the product name is different than the repository name.  

Can I suggest that we allow the import line to include the product name alternative as an optional value in the comment section?  E.g.

import ArgumentParser // apple/swift-argument-parser (ArgumentParser)

**Comment by c0diq** [comment]
This could be a good solution and would fix #119 as well if we could specify `(Path.swift)`

**Comment by c0diq** [comment]
FYI @cwoloszynski77 the issue with `ArgumentParser` is fixed with swift-sh 1.18.0 as far as I know.

**Comment by cwoloszynski** [comment]
I was using 1.18.0 when I found this.  I don’t think it is fixed yet, or I don’t understand what I needed to do to work around this issue.

**Comment by iT-Boyer** [comment]
> I was using 1.18.0 when I found this. I don’t think it is fixed yet, or I don’t understand what I needed to do to work around this issue.

me too

**Comment by adam-fowler** [comment]
@cwoloszynski @iT-Boyer the `ArgumentParser` issue is fixed with the github 1.18.0. Unfortunately the changes from github never made it into the homebrew v1.18.0. See #118.

 You can either install swift-sh using
```
brew reinstall --build-from-source mxcl/made/swift-sh
```
Or use [mint](https://github.com/yonaskolb/Mint) to install it. You'll have to uninstall the homebrew version if you use `mint`.

**Comment by cwoloszynski77** [comment]
Thanks for the update and helping track down this disconnect.

Your command fixed this for me!

Thanks!

Charlie

________________________________________________________________________

Charlie Woloszynski, Senior Member of the Technical Staff
p: +1.703.287.7439 | m: +1.703.989.4061 |  www.iridium.com<http://www.iridium.com/>

The information contained in this email is strictly confidential and may be legally privileged and protected from disclosure by law. This email is intended for use by the addressee only. Notice is hereby given that any disclosure, use or copying of the information by anyone other than the intended recipient is strictly prohibited and may be illegal. If you have received this email in error, please destroy all electronic and other copies of this message and contact the sender or Iridium at email@iridium.com
