### ISSUE TITLE
Xcode 12 beta 6 error message

### ISSUE THREAD

**Issue by Prince2k3** [mxcl/swift-sh#125]
Just a heads up. Now in  Xcode 12 b6 `v10_16` is deprecated and now must use `v11` for macOS going forward. 

The error message I'm getting now.
```
/Developer/swift-sh.cache/9883d732d6abfa92e768ffcfbdfce4c3/Package.swift:24:12: 'v10_16' has been renamed to 'v11'
```

**Comment by mxcl** [comment]
I just ran all the tests with Xcode 12b6 and did not see this error. How are you seeing this?

**Comment by Prince2k3** [comment]
I'm running my script in Xcode `Run Script Phase` and I'm on the beta version of macOS Big Sur. On my non beta laptop, you are right this doesn't happen with Xcode 12 b6 on macOS Catalina.

**Comment by Jeehut** [comment]
@mxcl @Prince2k3 Same issue here on macOS Big Sur Beta 8 and Xcode 12 beta command line tools.

**Comment by mxcl** [comment]
I believe this is a bug in SwiftPM since neither `v10_16` or `v11` are permitted:

```
Package.swift:24:12: error: 'v10_16' has been renamed to 'v11'
   .macOS(.v10_16)
           ^~~~~~
           v11
PackageDescription.SupportedPlatform:11:27: note: 'v10_16' has been explicitly marked unavailable here
        public static var v10_16: PackageDescription.SupportedPlatform.MacOSVersion
                          ^
```

vs:

```
Package.swift:24:12: error: 'v11' is unavailable
   .macOS(.v11)
           ^~~
PackageDescription.SupportedPlatform:13:27: note: 'v11' was introduced in PackageDescription 5.3
        public static var v11: PackageDescription.SupportedPlatform.MacOSVersion
                          ^
```

We cannot support PackageDescripton 5.3 easily. OTOH Xcode 12 was released with this bug so we’re probably stuck with it.

**Comment by Jeehut** [comment]
@mxcl What about switching to PackageDescription 5.3 in a branch that can be explicitly pointed to / installed when Xcode 12 support is needed? I'm assuming by "we cannot support" you mean "because we want to keep this backwards-compatible". Or is there any other reasons why PackageDescription 5.3 can't work?

**Comment by mxcl** [comment]
I said we cannot easily support, implying it is probably 40 hours of work.

Anyway, I pushed a fix that will do. Please try it out.
