### ISSUE TITLE
`swift sh edit script.swift` generates xcodeproj file incompatible with Xcode 11.6.

### ISSUE THREAD

**Issue by toastersocks** [mxcl/swift-sh#126]
When trying to edit a script using `swift sh edit script.swift` an error dialog pops up in Xcode 11.6 (the latest stable version as of this writing) that says the project can't be opened because it was created using a "future version" of Xcode.
<img width="488" alt="The project at 'script.xcodeproj' cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode." src="https://user-images.githubusercontent.com/574947/91754307-0cb7cc00-eb7e-11ea-824e-6459519af292.png">
Opening the project in Xcode 12 beta 6, and resetting the Xcode project compatibility version to '11.4' fixes the issue, however the initial value shown is Xcode version '9.3' so this seemingly should be compatible without needing to adjust the setting in Xcode 12.

swift-sh version: 2.0.1
macOS: 10.15.6
Xcode: 11.6

**Comment by toastersocks** [comment]
Looks like a quick fix is opening up the `project.pbxproj` file in the xcodeproj bundle and changing the `objectVersion` key from 54 to 53 enables the project to open in Xcode 11.6.

**Comment by sergiobaro** [comment]
Hi, I have the same problem on Xcode 11.7
![Screenshot 2020-09-04 at 12 51 18](https://user-images.githubusercontent.com/1587104/92231790-ab5d6900-eead-11ea-9af0-44f66e5481a6.png)

The same fix works for me, just changing the `objectVersion` to 53 instead of 54.

swift-sh version: 2.0.1
macOS: 10.15.6
Xcode: 11.7

**Comment by jsorge** [comment]
I'm seeing this as well.

swift-sh version: 2.0.1
macOS: 10.15.6
Xcode: 11.6

**Comment by jsorge** [comment]
It looks like the tuist/Xcodeproj dependency updated that from 51 to 54 a few months ago (https://github.com/tuist/XcodeProj/blob/master/Sources/XcodeProj/Project/Xcode.swift#L29) and that's where things started breaking.

**Comment by mxcl** [comment]
Supposedly fixed in 2.1.0, please confirm.

**Comment by sergiobaro** [comment]
I have tested 2.1.0 and it's working for me.
Thank you!
