### ISSUE TITLE
Something odd about the 2.2.0 release brew record

### ISSUE THREAD

**Issue by haikusw** [mxcl/swift-sh#141]
I'm not sure how brew works but it's showing  as version 2.1.0 in some places but 2.2.0 in others.
This is from a native Apple Silicon install on macOS 11.1 (so you'll see that it's in /opt/homebrew/…).
This issue is also present on an Intel based Mac where it's installed in /usr/local.

It _does_ seem to be version 2.2.0 because it works on the M1 / Apple Silicon Mac so it has the 2.2.0 fixes.  So just the swift-sh brew info record, seems like.

> % brew list --version     
> …
> **swift-sh 2.2.0**
> …
> % brew info swift-sh
> swift-sh: stable **2.1.0** (bottled), HEAD
> Scripting with easy zero-conf dependency imports
> https://github.com/mxcl/swift-sh
> /opt/homebrew/Cellar/swift-sh/**2.2.0** (6 files, 6.2MB) *
>   Built from source on 2021-01-06 at 12:40:44
> From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/swift-sh.rb
> License: Unlicense
> ==> Requirements
> Build: Xcode >= 11.0 ✔
> ==> Options
> --HEAD
> 	Install HEAD version
> ==> Analytics
> install: 98 (30 days), 282 (90 days), 768 (365 days)
> install-on-request: 98 (30 days), 283 (90 days), 760 (365 days)
> build-error: 0 (30 days)
>

**Comment by helje5** [comment]
BTW: This does seem to work now for me on M1, w/ the /usr/local Rosetta Homebrew. Just did a brew update&upgrade and it seems to have arrived properly.
```
helge@M1ni ~ $ brew info swift-sh

swift-sh: stable 2.2.0 (bottled), HEAD
Scripting with easy zero-conf dependency imports
https://github.com/mxcl/swift-sh
/usr/local/Cellar/swift-sh/2.2.0 (6 files, 6.2MB) *
  Poured from bottle on 2021-01-08 at 15:28:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/swift-sh.rb
License: Unlicense
==> Requirements
Build: Xcode >= 11.0 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 126 (30 days), 322 (90 days), 812 (365 days)
install-on-request: 126 (30 days), 323 (90 days), 804 (365 days)
build-error: 0 (30 days)
```

**Comment by haikusw** [comment]
Seems to be fixed here now also.  sweet!
