### ISSUE TITLE
Change version to 11

### ISSUE THREAD

**Issue by Qusea** [mxcl/swift-sh#144]
When I try to run swift sh I get this error

Package.swift:24:13: error: 'v10_16' has been renamed to 'v11'
    .macOS(.v10_16)
            ^~~~~~
            v11
PackageDescription.SupportedPlatform:11:27: note: 'v10_16' has been explicitly marked unavailable here
        public static var v10_16: PackageDescription.SupportedPlatform.MacOSVersion

but if I manually the version to 11 and swift tools version to. 5.3 it works perfectly

**Comment by mxcl** [comment]
Pretty hard to fix or help since you provided no information about your configuration. Closing.
