### ISSUE TITLE
Fail to import when the package-name and repo-name are not identical

### ISSUE THREAD

**Issue by xareelee** [mxcl/swift-sh#145]
I use  [swift-sh](https://github.com/mxcl/swift-sh) successfully to import other libs, but not [EonilFSEvents](https://github.com/eonil/FSEvents).

```swift
#!/usr/bin/swift sh

import Foundation
import PromiseKit  // @mxcl ~> 6.5
import EonilFSEvents  // eonil/FSEvents ~> 0.1
```

It shows an error while importing after successfully resolving dependencies:

```
Updating https://github.com/mxcl/PromiseKit.git
Fetching https://github.com/eonil/FSEvents.git
Cloning https://github.com/eonil/FSEvents.git
Resolving https://github.com/eonil/FSEvents.git at 0.1.7
'your-swift-script' path-to/swift-sh.cache/49e96c02cae55802c8b6c24fbe5d3972: error: product dependency 'EonilFSEvents' in package 'FSEvents' not found
error: 1 <(/usr/bin/swift build -Xswiftc -suppress-warnings)
```

After downloading `EonilFSEvents` and trying to load it locally, I find the problem. The package name in `Package.swift` doesn't match the repo name `FSEvents` which `swift-sh` is trying to find:

```swift
// Package.swift in eonil/FSEvents

let package = Package(
    name: "EonilFSEvents",
    ...
)
```

To resolve this problem manually, I need to either:

- change the `name` in `Package.swift` to match its folder name, or
- change the folder name to match the `name` in `Package.swift` 

I think that `swift-sh` should support redirecting the package name (for example, using `#` as below):

```
import EonilFSEvents  // eonil/FSEvents #EonilFSEvents ~> 0.1
// ^^ for when the package-name and repo-name are not identical
```

There are three names that may not be identical:

1. module name: which you import
2. package name: which is defined in `Package.swift`
3. repo name (or folder name): where the repo is

**Comment by mxcl** [comment]
Yeah, this is a fundamental issue with `swift-sh`.
