### ISSUE TITLE
Brew complaining about outdated formula syntax

### ISSUE THREAD

**Issue by haikusw** [mxcl/swift-sh#148]
> Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the mxcl/made tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/mxcl/homebrew-made/swift-sh.rb:9

> Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the mxcl/made tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/mxcl/homebrew-made/swift-sh.rb:10

**Comment by mxcl** [comment]
Try 2.3.0, reopen if not fixed.
