### ISSUE TITLE
Error during installation: Invalid bottle tag symbol

### ISSUE THREAD

**Issue by ataourirt** [mxcl/swift-sh#152]
Hi!

`brew install mxcl/made/swift-sh` not working

<img width="574" alt="Capture d’écran 2021-05-17 à 15 58 47" src="https://user-images.githubusercontent.com/16756293/118501244-cf559780-b728-11eb-9c04-3a17a906201f.png">

Thanks

**Comment by mxcl** [comment]
Try 2.3.0, reopen if not fixed.
