### ISSUE TITLE
PathKit dependency needs to be updated to 1.0.1

### ISSUE THREAD

**Issue by rayray** [mxcl/swift-sh#176]
I can't find where the `PathKit` dependency is actually listed, but it's in the `Package.resolved`. 

`PathKit` created the `1.0.1` release to resolve Xcode 13 build issues: https://github.com/kylef/PathKit/releases/tag/1.0.1

I opened this issue in the Homebrew `swift-sh` repo because I cannot install `swift-sh` via `brew` with Xcode 13. https://github.com/mxcl/homebrew-made/issues/12

**Comment by mxcl** [comment]
This is fixed here and the formula is being updated concurrently
