### ISSUE TITLE
Configurable templates/context

### ISSUE THREAD

**Issue by wti** [mxcl/swift-sh#189]
It's likely a pain to track swift/swiftpm versions and user packaging desires.

Using extensible templates and context might help.

The core workflow of swift-sh works great, but the dependency parsing and Package.swift generation is static while swift/swiftpm versions and user needs grow and vary.  To support existing users, swift-sh targets the oldest version possible, which constrains features.
 
If/since Package.swift is a function of the template and context variables, making each of those extensible/configurable should help, and may drive features. Users would use external templates, and then contribute them to swift-sh to include in resources as available templates triggered by higher-level flags/conditions (like tools-version).

This is to propose initial steps to template-generation, with minimal CLI support for extending context, but
- no changes to parsing
- no/minimal changes to existing default code path for the interpolated template

## Context & CLI
- Support context specified on the command-line (in the shebang line)
- Context initially just -Dname=value pairs
- Template flag with script-relative template path

## Templates
1. `Script.write()` can migrate to a static method taking the script package metadata and template configuration.  
2. The default is the current string interpolation, but configuration can specify any template.  
3. Unit tests can target the static method, e.g., comparing vetted and new variants

### Design/staging plan, to review and agree...
1. Settle on a template facility (homegrown or library - Stencil?)
2. Review/modify the script metadata for usability in templates and extensibility via command-line
    - Keep current parser, just repackage metadata if needed
    - The model is detailed but constrained by swiftpm; dependency versions are a PITA to avoid for now
3. Integrate
4. Test

Some non-required features to consider hoisting for testability:
- template dir: local template access by name relative to dir
- preflight mode to generate but not build

Testing:
- CLI, context parsing, and template generation can all be unit tested
- integration tests using all available context, minimum viable context, and (error case for) missing context

Nice to have:
- Demo package for user script template proposals

Constraints:
- Support the present behavior exactly when unconfigured, using no new code paths.  Users must opt in to new code.
- No changes to context available via parsing (initially)
- My time is pretty limited, so roll out incrementally with optional/opt-in CLI parameters, working in branch with milestone and releasable tags

Please let me know if you have time/interest/schedule for settling on a plan and reviewing work in branch.

**Comment by wti** [comment]
<https://github.com/swift-nest/clutch> lets the user define the package structure for scripts.

**Comment by mxcl** [comment]
Great work. Version it and I'll add it to pkgx.sh

**Comment by wti** [comment]
Thanks for the offer!  

Not sure what version is required.  It's tagged (currently 0.5.2) to work with swift package manager.  I didn't see docs on point at pkgx.sh, and I couldn't glean anything relevant from the package.yml for a swift tool in the pantry (tart): 

https://github.com/pkgxdev/pantry/blob/main/projects/tart.run/package.yml

**Comment by mxcl** [comment]
Oh I see, yeah typically when I visit a project and there are zero releases I assume it hasn't been released yet, but I see there are tags and that is indeed enough.
