### ISSUE TITLE
Caches directory?

### ISSUE THREAD

**Issue by svdo** [mxcl/swift-sh#20]
Great initiative, I love it!

Just for your consideration: on macOS it feels more logical to me to use `.cachesDirectory` instead of `.itemReplacementDirectory` for the location of the downloaded dependencies.

Thanks!!

**Comment by mxcl** [comment]
We only use this in the tests, the cache directory we use for downloaded dependencies is listed in the README.

**Comment by mxcl** [comment]
https://github.com/mxcl/swift-sh/blob/master/README.md#internal-details
