### ISSUE TITLE
readLine() does not return

### ISSUE THREAD

**Issue by francybiga** [mxcl/swift-sh#21]
I have this simple script which should get user input using `readLine()`:

```
print("Enter name:")
if let name = readLine() {
    print("Entered \(name)")
}
```

When I run it using plain Swift (`swift script.swift`) it works as expected, but when I run it using `swift-sh` it hangs on `readLine()` despite I type a string and hit Enter.

Executing `swift build;swift run` in `~/Library/Developer/swift-sh.cache/scriptName` (which, as I understand, is what `swift-sh` does behind the scene) it works as expected (read and prints the string).

Am I missing something?

**Comment by mxcl** [comment]
Hmm weird. All we do is call `swift run` ourselves. But I don't use exec, possibly that is the problem. Will try it.

**Comment by mxcl** [comment]
Yeah this fixes it. Update incoming!

**Comment by mxcl** [comment]
Waiting on: #22

**Comment by francybiga** [comment]
Great! 👍

**Comment by mxcl** [comment]
Updates available via all methods, thanks for the report x
