### ISSUE TITLE
Feature Request: Support command line arguments

### ISSUE THREAD

**Issue by EricKuck** [mxcl/swift-sh#26]
You can only do so much without being able to pass in arguments.

**Comment by mxcl** [comment]
Will do this today.

**Comment by EricKuck** [comment]
This is amazing! Thanks so much for the quick work.

**Comment by mxcl** [comment]
No problem. If you found my help useful, please consider reimbursing my time by contributing to [my Patreon](https://patreon.com/mxcl).
