### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by mgrebenets** [mxcl/swift-sh#3]
Hi.

It doesn't seem to work behind the proxy. E.g. doesn't seem to respect `HTTP(S)_PROXY/i` vars configured in my shell session.

It looks like it's using `swift build` under the hood and I don't remember if that needs some flags to work with proxy.

**Comment by mgrebenets** [comment]
Yep, we've got on Swift package depending on Result package, running `swift build` from command line outputs this:

```
╰─$ swift build
Fetching https://github.com/antitypical/Result.git
Completed resolution in 4.81s
Cloning https://github.com/antitypical/Result.git
Resolving https://github.com/antitypical/Result.git at 3.2.4
```

The error I get with `swift-sh` is this at the moment:

```
╰─$ swift-sh swiftsh.swift
Fetching /Users/bigmac/Library/Developer/swift-sh.cache/swiftsh/mxcl/PromiseKit
error: failed to clone; fatal: repository '/Users/bigmac/Library/Developer/swift-sh.cache/swiftsh/mxcl/PromiseKit' does not exist
'swiftsh' /Users/bigmac/Library/Developer/swift-sh.cache/swiftsh: error: product dependency 'PromiseKit' not found
```

That's why I assumed that cloning failed, though I'm not 100% sure about that.

I can see `Process` class being used to run the `swift build`.
Is that part of `Foundation` framework or a 3rd party dependency?

**Comment by mxcl** [comment]
This is a bug I fixed a few hours ago, please update.

**Comment by mgrebenets** [comment]
I see, I'm on 1.1.1 while there's 1.1.2.
I guess I have to wait until it gets populated?
Running brew install or brew upgrade for mxcl/made/swift-sh tells me 1.1.1 is the latest.

I'll try later anyways, thanks for the help 👍

**Comment by mxcl** [comment]
Ugh, sorry I didn't push to my homebrew tap. It's live now, `brew upgrade swift-sh` should do it.

I intend to automate the brew part.

**Comment by mgrebenets** [comment]
Looks good now, get all the source downloaded.
I'm trying to run an example with `PromiseKit`.
First I had to add `Foundation` import, since all the basic types would not be found by compiler.

Got it down to this so far:

```swift
#!/usr/bin/swift sh

import Foundation
import PromiseKit  // @mxcl ~> 6.5

let url = URL(string: "https://github.com/mxcl/swift-sh")!
let request = URLRequest(url: url)
firstly {
    URLSession.shared.dataTask(.promise, with: request)
}.then {
    after(.seconds(2))
}.done {
    print("Scripts with package dependencies!")
    exit(0)
}

RunLoop.main.run()

```

However, the PromiseKit extensions for `URLSession` are note there (according to compiler).

```
╰─$ swift-sh swiftsh.swift
Compile Swift Module 'swiftsh' (1 sources)
/Users/bigmac/Library/Developer/swift-sh.cache/swiftsh/main.swift:8:23: error: argument labels '(_:, with:)' do not match any available overloads
    URLSession.shared.dataTask(.promise, with: request)
                      ^       ~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/bigmac/Library/Developer/swift-sh.cache/swiftsh/main.swift:8:23: note: overloads for 'dataTask' exist with these partially matching parameter lists: (with: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void), (with: URL, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void)
    URLSession.shared.dataTask(.promise, with: request)
                      ^
error: terminated(1): /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/bigmac/Library/Developer/swift-sh.cache/swiftsh/.build/debug.yaml swiftsh.exe output:
    Compile Swift Module 'swiftsh' (1 sources)
    /Users/bigmac/Library/Developer/swift-sh.cache/swiftsh/main.swift:8:23: error: argument labels '(_:, with:)' do not match any available overloads
        URLSession.shared.dataTask(.promise, with: request)
                          ^       ~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/bigmac/Library/Developer/swift-sh.cache/swiftsh/main.swift:8:23: note: overloads for 'dataTask' exist with these partially matching parameter lists: (with: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void), (with: URL, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void)
        URLSession.shared.dataTask(.promise, with: request)
```

This is unlrelated to the original issue though.

**Comment by mxcl** [comment]
Oh my bad, the example script needs:

    import PMKFoundation // @PromiseKit ~> 3

**Comment by mgrebenets** [comment]
Cool, though doesn't look like v3 has SPM manifest:

```
Updating https://github.com/mxcl/PromiseKit.git
https://github.com/mxcl/PromiseKit.git @ 3.5.3: error: https://github.com/mxcl/PromiseKit.git has no manifest for version 3.5.3
```

**Comment by mxcl** [comment]
I think you edited the PromiseKit specification instead of adding the PMKFoundation specification line I provided.

Anyway it still fails due to a limitation specified in the README. (The PMKFoundation module name is not the same as Package.swift name).

I recommend testing with more conventional libraries, I'll amend the README so it works.

**Comment by mxcl** [comment]
Sorry for the issues, I literally started this project about 30 hours ago. Heh. LMK if you have any other troubles.

**Comment by mxcl** [comment]
Like here's a simple example script that works:

```swift
#!/usr/bin/swift sh
import Foundation
import Result  // @antitypical ~> 4.1

print(Result<Int, CocoaError>.success(3))
```

**Comment by mxcl** [comment]
K I have fixed the issue that meant importing `PMKFoundation` wouldn't work, coming in 1.1.3
