### ISSUE TITLE
swift-sh VS Beak VS Marathon

### ISSUE THREAD

**Issue by acecilia** [mxcl/swift-sh#47]
Hi:

Just discovered swift-sh, and I am going to be using it very soon to switch my build scripts from bash to swift. Thanks!
I was reading the readme, and also found Marathon and Beak. After reading their readme, seems to me that everything that swift-sh can do, also Beak or Marathon can. Plus Beak offers the command line interface for free.

So, in what is swift-sh different than Marathon or Beak?
Thanks!

**Comment by mxcl** [comment]
It’s your preference, use whichever one you like.

**Comment by acecilia** [comment]
Thanks!
