### ISSUE TITLE
Feature Request: Editor/IDE/LSP support

### ISSUE THREAD

**Issue by markmals** [mxcl/swift-sh#53]
When working on a swift-sh script in VS Code with sourcekit-lsp running, I get a few "No module found" errors for the `import`s intended to be resolved by swift-sh. I'm assuming this is because the packages don't get fetched/cached until the script is first run and/or because sourcekit-lsp doesn't know where the cache is located, in order to pull in module interfaces.

Would it be possible to automate fetching, caching, and pointing sourcekit-lsp to cached packages as part of swift-sh? If not, would it be possible to do it with an external VS Code extension?

**Comment by mxcl** [comment]
No clue, have no familiarity with vs-code or sourcekit-lsp.

**Comment by shankaryoga** [comment]
Give guidance

**Comment by kabouzeid** [comment]
`swift sh edit` should use `$EDITOR`.
XCode is pretty slow to start up.
This way, we can use vim or vscode to edit our files with LSP support.

**Comment by mxcl** [comment]
If you want to use vim, just do `vim my-script`. The whole point in `swift sh edit` is to use Xcode so you get completion and inline errors.

**Comment by kabouzeid** [comment]
`vim my-script` won't give me completions. The LSP in vim then doesn't find `Package.swift`.
If I cd to `~/Library/Developer/swift-sh.cache/<script>` and then use `vim main.swift` I get completions in vim via LSP.

**Comment by mxcl** [comment]
PR welcome… `swift sh edit` as it stands only supports Xcode, I have no idea how to make it work with `vim` so if you want that, submit the PR.

**Comment by kabouzeid** [comment]
Alright, I'll start working on it.

**Comment by kabouzeid** [comment]
https://github.com/mxcl/swift-sh/pull/85

**Comment by mxcl** [comment]
Merged! Thanks
