### ISSUE TITLE
Swift sh conflict with previous cache

### ISSUE THREAD

**Issue by Larmichou** [mxcl/swift-sh#67]
I really like the `swift sh edit myFile.swift`, and use it quite a lot now.

But I got an issue:

```
$>swift sh edit MyFile.swift 
error: The file “main.swift” couldn’t be saved in the folder “MyFile” because a file with the same name already exists.
```

First, I'd like to know where is that cache.

Second, is there a way to indicate in the error, as a suggestion, where is located the cache so I can remove it manually (maybe also suggest a `rm` command with the correct path?

**Comment by mxcl** [comment]
The cache location is listed in the README.

Thanks for the report, I'll take a look.

**Comment by mxcl** [comment]
I cannot reproduce this error, do you know any more information about how it occurred?

**Comment by Larmichou** [comment]
Sorry, I missed that [part](
https://github.com/mxcl/swift-sh#internal-details), I was focused on [this](
https://github.com/mxcl/swift-sh#editing-in-xcode) 

I'll try to make steps to reproduce when possible.

**Comment by mxcl** [comment]
I agree the error should be more useful, however this would be quite a large project, the error occurs inside Foundation, to do useful errors everywhere I’d have to figure out the errors that may be thrown for every line of code, catch them, re-interpret them into better errors and re-throw. It’s not trivial and frankly quite hard to validate.

**Comment by tcamin** [comment]
This happened to me as well, in my case it was due to the fact that the symlinked file main.swift points to no longer existed (I changed paths).

**Comment by tcamin** [comment]
Apparently Path `delete()` method implementation checks if the file exists before using FileManager to actually delete it. However existence is resolves against the symlinked file, not the symlink itself. 

A naive fix would be to use FileManager to delete the mainSwift in Scripts.swift:66. @mxcl how would you suggest to workaround this issue? I can happily open a PR.

**Comment by mxcl** [comment]
Well, this is a bug in `Path.swift` then.

**Comment by mxcl** [comment]
https://github.com/mxcl/Path.swift/pull/47
