### ISSUE TITLE
Specify macos deployment target

### ISSUE THREAD

**Issue by julianmee** [mxcl/swift-sh#72]
Hello,

i have a problem on running swift-sh scripts with dependencies that uses `@available(macOS 10.13, *)
`
If i run the script, the swift compiler always deploy it with deployment target "macos 10.10". How can force swift-sh to compile it with another deployment target.

Thank you,
  Julian

**Comment by mxcl** [comment]
That would require Swift 5 SwiftPM, but then we could add deployment targets. The question is how we should go about that.

We *could* default to the macOS version the script is run upon. But would that suffice?

**Comment by omochi** [comment]
I faced same issue.
I think that specifying current macOS version is good.
Because compiled `swift-sh` binary would not be distributed to other machines.

**Comment by mxcl** [comment]
We now do this.
