### ISSUE TITLE
Import local packages

### ISSUE THREAD

**Issue by jasonzurita** [mxcl/swift-sh#76]
First off, I think swift-sh rocks! I have been enjoying scripting in Swift for a little while now, but this project really takes it to the next level — thanks!

When developing a Swift package locally, I would like to be able to invoke it using swift-sh. i.e., allow swift-sh to take in a local swift packages.

e.g., ```import Foo // ~/Desktop/Foo```

I am using tests to do most of my local development, but I would like to also test my swift package using swift-sh as a real _production_ test. I plan on uploading my project to Github, which would allow swift-sh to grab it, but I would rather not have to rely on that workflow; Especially when making small incremental changes.

I looked through the source code a bit, and I don't think this is currently possible based on: https://github.com/mxcl/swift-sh/blob/acf0a1c78fac3254c04926f65812b121f5be5447/Sources/Script/ImportSpecification.swift#L102

I could be wrong though 😅.

I also came across this closed issue: https://github.com/mxcl/swift-sh/issues/17, but that issue is related to local files.

**Comment by mxcl** [comment]
PR welcome

**Comment by jasonzurita** [comment]
Cool, sounds great!

I will see what I can figure out and report back :).

**Comment by mxcl** [comment]
SwiftPM supports local dependencies so can be done. I think the issue will be the syntax to ensure there is no conflict with the form: `import Foo  // bar/baz` we may need to change this to be `@bar/baz` which requires a breaking change.

**Comment by jasonzurita** [comment]
Yeah, I went into the swift-sh cache and manually edited the `Package.swift` to make sure my local dependency worked.

As far as the syntax goes, good point.
- Is there any desire to prevent that breaking change?
- Maybe we could relying on a prefix like `~` or `local:`?
  (I am not sure how I feel about this yet though)

**Comment by mxcl** [comment]
> “Is there any desire to prevent that breaking change?”

Ideally, but I'm not sure it will be possible without having it do some kind of check if a directory exists which means our behavior is flakey depending on your directory layouts.

**Comment by jasonzurita** [comment]
@mxcl After looking into this a bit, I would like your thoughts on the following:

I can move the package _url_ logic from `ImportSpecification` to `parse().swift` and do something like:
```let depUrlString: String
    if depSpec.hasPrefix("@") {
        let depName = String(depSpec.dropFirst())
        if let url = URL(string: depName), url.scheme != nil {
            depUrlString = depName
        } else {
            depUrlString = """
            https://github.com/\(depName + "/" + importName).git
            """
        }
    } else {
        depUrlString = String(depSpec)
    }
```

This would replace the _dependencyName_ property in `ImportSpecification` with a different property like _dependencyUrlString_, and `var packageLine: String` would just use the _dependencyUrlString_ (the result from the above change) for the package _url_. This is assuming the current _dependencyName_ property is not (or will not be) needed elsewhere.

Another potential solution would be to create a new `DependencySource` enum (e.g., github, local, etc.) that has the _dependencyName_ as an associated value, which would replace the _dependencyName_ property in `ImportSpecification`. This would then be used to switch over in `var packageLine: String` to produce the package _url_. This would probably be a bit cleaner, but more involved. I am open to doing this if there is a benefit to keeping the _dependencyName_ property around.

Both solutions above would have `@` signify a GitHub dependency, which would be a breaking change as you said.

Thoughts?

**Comment by mxcl** [comment]
Going through this code I have to apologize, it's not great. Was a quick project TBH.

Yeah, as you concluded `ImportSpecification` will need to change, which is fine. Seems like an `enum` to replace `dependencyName` would do the trick:

```swift
enum Dependency {
    case remote(URL)
    case local(Path)
}
```

Even though most people would (probably) specify local paths relatively, we need the full path since we write the Package.swift elsewhere, which is a pity (since paths change), but not much can be done.

Then change the property name to `let dependency: Dependency` I guess.

> Both solutions above would have @ signify a GitHub dependency, which would be a breaking change as you said.

I think we will do a gradual roll out. For now we should check if a package exists at that path and if so, use `.local`, otherwise behave like it does now (GitHub URL) but output a warning.

We shouldn’t break scripts for everyone instantly if possible.

**Comment by jasonzurita** [comment]
Hey, just wanted to give a quick update.

I made some progress changing `dependencyName` over to a new `Dependency` enum to accommodate this change, but paused to see the fallout from the _private repos_ issue: https://github.com/mxcl/swift-sh/issues/77 (great stuff btw!).

I have to fully catch up and do some rework where necessary, but I am very much still working on this :).

**Comment by mxcl** [comment]
Yeah, sorry, I was thinking of you while I was doing it, unfortunate timing.

**Comment by jasonzurita** [comment]
Haha, no worries. And yeah I do think my work will fit in better now — nice cleanup PR!

**Comment by jasonzurita** [comment]
Just submitted PR https://github.com/mxcl/swift-sh/pull/81 to resolve this issue. Let me know what you think!
