### ISSUE TITLE
CI/Deployment/Actions

### ISSUE THREAD

**Issue by mxcl** [mxcl/swift-sh#9]
- [x] Update Linux tests on push
- [x] Update Homebrew formula on release
- [x] Only run Travis for releases, PRs and merge commits

**Comment by mattt** [comment]
>  [ ] Update Homebrew formula on release

Once [GitHub actions](https://github.com/features/actions/) supports [`release`](https://developer.github.com/v3/activity/events/types/#releaseevent) (the current Beta is limited to `push` events only), it'll be much easier to sync (all) Homebrew formulae with tagged releases.

No public announcements yet about when that will be available, but you may consider deferring until then to avoid an intermediate solution.

**Comment by mxcl** [comment]
f3349445bd88aeeca2d59582c93840bd34d733ec
