### ISSUE TITLE
Translate `.` in user/org names to `-`

### ISSUE THREAD

**Issue by helje5** [mxcl/swift-sh#98]
When you create an organisation in GitHub, you can use a `.` in the name, say: `Macro.swift`. GitHub translates that to a `-`.
Would be cool if swift-sh would allow that as well. Currently it gives a:
```
error: The operation couldn’t be completed. (E.invalidGitHubUsername("Macro.swift"))
```

**Comment by mxcl** [comment]
Please review #100, though I already merged it.
